Custom/javascript improvements
tfso/eslint-config-tfso pull request #6
Opened 2022-04-29 16:34 UTC by edgarbjorntvedt

* moved rule: "no-unused-vars" to default rule (includes javascript as well)
* adding mocha as environment in order to support "it", "describe" ..

2022-06-08 10:14 UTC, lostfields reviewed
hmm, jeg mener bastant at det er noe som varsler om ubrukte variabler når jeg skriver kode, og utifra dette så ser det jo ut som at det ikke er eslint som gjør det!?

2022-06-12 16:54 UTC, edgarbjorntvedt commented
jeg vet ikke, men jeg er enig med deg. Jeg forsøker bare her å gjøre koden mer uniform. Noe imot at jeg merger?

2022-06-21 11:20 UTC, lostfields requested changes
Hvis denne skrues av, så vil den ikke lengre advare om ubrukte variabler i javascript. Ønsker vi det?

2022-06-21 11:24 UTC, lostfields requested changes
tidligere funksjonalitet fjernes fra JS og typescript-regelen avhenger av at javascript rules har satt `no-unused-vars` av.

2022-06-21 11:24 UTC, lostfields commented on default.js
> +        "no-unused-vars": "off",
Hvis denne skrues av så vil ikke lengre javascript advare om ubrukte variabler, ønsker vi egentlig det?

2022-06-21 11:24 UTC, lostfields commented on typescript.js
> -
Denne er skrudd av for javascript, fordi typescript har sin egen regel for [no-unused-vars ](https://typescript-eslint.io/rules/no-unused-vars/). Denne blir arvet fra `plugin:@typescript-eslint/recommended`

2022-06-22 12:16 UTC, edgarbjorntvedt commented on typescript.js
> -
ok, da blir det vel mest riktig å fjerne denne

2022-06-23 09:03 UTC, lostfields commented on typescript.js
> -
i `default.js` så ligger det `"no-unused-vars": "warn",` og for at det ikke skal bli konflikt mellom typescript og javascript-regler så må javascript varianten skrues av, slik at typescript skal fungere slikt den er tiltenkt. Ellers blir det dobbel med lintefeil osv.

2022-06-23 11:22 UTC, edgarbjorntvedt commented
Så denne PRen blir bare feil? (jeg tror ikke jeg skjønner dette) I så fall er det bar å close hele PRen da..

2022-06-23 17:21 UTC, lostfields commented
> Så denne PRen blir bare feil? (jeg tror ikke jeg skjønner dette) I så fall er det bar å close hele PRen da..

Nei, men du må skrive en `fix:`, `feat:` eller noe slikt i en commit bare. Men ta en titt på den kommentaren min på no-unused-vars

2022-06-24 08:45 UTC, edgarbjorntvedt commented on typescript.js
> -
endelig så jeg at du hadde linket inn https://typescript-eslint.io/rules/no-unused-vars/ Først nå skjønte jeg hva vi snakket om

2022-06-24 10:13 UTC, lostfields approved these changes

2022-07-25 05:26 UTC, merged